#include "config.h"

Config::Config()
{
  CONFIG_DEBUG = true;
  CONFIG_GENERATIONS_PRINT = false;
  CONFIG_RESULT_SUMMARY = true;
  CONFIG_PMUT = 70;
  CONFIG_MUTAGENES = 1;
  CONFIG_TOUR = 4;
  CONFIG_POPSIZE = 6;
  CONFIG_LAMBDA = 20;
  CONFIG_GENERATIONS = 20000;
  CONFIG_EVOLUTION_TYPE = "ES"; // ES or GA
  INPUT_FILE = "dataset/LC1_2_1.txt";
  unit = 100;
}